services:
  app:
    build:
      args:
        APP_PORT: 8080
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reservas
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      JWT_SECRET: "SECRETO_JWT_EN_BASE64_O_TEXTO_LARGO" #
      JWT_EXPIRATION_MS: 86400000
      # Para cambiar entre debug y prod sin reconstruir la imagen Docker:
      JVM_OPTS_PROFILE: "debug"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # Da tiempo a que la app arranque

  db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=reservas'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
